//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Web.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASSEMENT
    {
        public CLASSEMENT()
        {
            this.T_J_GENERATION_GEN = new HashSet<GENERATION>();
        }
    
        public int CLA_ID { get; set; }
        public Nullable<int> CLA_TEMPS { get; set; }
    
        public virtual ICollection<GENERATION> T_J_GENERATION_GEN { get; set; }
    }
}
