//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Web.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE
    {
        public COURSE()
        {
            this.T_J_GENERATION_GEN = new HashSet<GENERATION>();
            this.T_J_PARTICIPATION_PAR = new HashSet<PARTICIPATION>();
            this.T_J_PARTICIPATIONENGROUPE_PEG = new HashSet<PARTICIPATIONENGROUPE>();
            this.T_R_BORNE_BOR = new HashSet<BORNE>();
            this.T_R_DEFI_DEF = new HashSet<DEFI>();
        }
    
        public int COR_ID { get; set; }
        public string COR_NOM { get; set; }
        public int COR_DISTANCE { get; set; }
        public Nullable<System.DateTime> COR_DATE { get; set; }
        public Nullable<int> COR_NOMBREMAXPARTICIPANT { get; set; }
        public Nullable<decimal> COR_PRIX { get; set; }
    
        public virtual ICollection<GENERATION> T_J_GENERATION_GEN { get; set; }
        public virtual ICollection<PARTICIPATION> T_J_PARTICIPATION_PAR { get; set; }
        public virtual ICollection<PARTICIPATIONENGROUPE> T_J_PARTICIPATIONENGROUPE_PEG { get; set; }
        public virtual ICollection<BORNE> T_R_BORNE_BOR { get; set; }
        public virtual ICollection<DEFI> T_R_DEFI_DEF { get; set; }
    }
}
