//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Web.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEDERATION
    {
        public FEDERATION()
        {
            this.T_E_COUREUR_COU = new HashSet<COUREUR>();
            this.T_R_CLUB_CLU = new HashSet<CLUB>();
        }
    
        public int FED_ID { get; set; }
        public string FED_NOM { get; set; }
    
        public virtual ICollection<COUREUR> T_E_COUREUR_COU { get; set; }
        public virtual ICollection<CLUB> T_R_CLUB_CLU { get; set; }
    }
}
