//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Web.App_Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class INSCRIT
    {
        public INSCRIT()
        {
            this.T_E_COUREUR_COU = new HashSet<COUREUR>();
            this.T_R_CLUB_CLU = new HashSet<CLUB>();
        }
    
        public int INS_ID { get; set; }

        [Required]
        [EmailAddress]
        [StringLength(255)]
        public string INS_LOGIN { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [StringLength(255, MinimumLength = 6)]
        public string INS_MDP { get; set; }
        public int INS_NIVEAUAUTHENTIFICATION { get; set; }
    
        public virtual ICollection<COUREUR> T_E_COUREUR_COU { get; set; }
        public virtual ICollection<CLUB> T_R_CLUB_CLU { get; set; }
    }
}
