//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Web.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarathonEntities : DbContext
    {
        public MarathonEntities()
            : base("name=MarathonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COUREUR> COUREURs { get; set; }
        public virtual DbSet<INFORMATIONPUBLIQUE> INFORMATIONPUBLIQUEs { get; set; }
        public virtual DbSet<INSCRIT> INSCRITs { get; set; }
        public virtual DbSet<PAIEMENT> PAIEMENTs { get; set; }
        public virtual DbSet<PARTICIPATION> PARTICIPATIONs { get; set; }
        public virtual DbSet<PASTAPARTY> PASTAPARTies { get; set; }
        public virtual DbSet<CLASSEMENT> CLASSEMENTs { get; set; }
        public virtual DbSet<TEMPSCOUBORNE> TEMPSCOUBORNEs { get; set; }
        public virtual DbSet<BORNE> BORNEs { get; set; }
        public virtual DbSet<CATEGORIE> CATEGORIEs { get; set; }
        public virtual DbSet<CLUB> CLUBs { get; set; }
        public virtual DbSet<COURSE> COURSEs { get; set; }
        public virtual DbSet<DEFI> DEFIs { get; set; }
        public virtual DbSet<LOT> LOTs { get; set; }
    }
}
