//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Web.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAIEMENT
    {
        public PAIEMENT()
        {
            this.T_J_PARTICIPATION_PAR = new HashSet<PARTICIPATION>();
            this.T_J_PARTICIPATIONENGROUPE_PEG = new HashSet<PARTICIPATIONENGROUPE>();
        }
    
        public int PAI_ID { get; set; }
        public int PAI_MONTANT { get; set; }
        public string PAI_MOYENDEPAIEMENT { get; set; }
        public System.DateTime PAI_DATEPAIEMENT { get; set; }
    
        public virtual ICollection<PARTICIPATION> T_J_PARTICIPATION_PAR { get; set; }
        public virtual ICollection<PARTICIPATIONENGROUPE> T_J_PARTICIPATIONENGROUPE_PEG { get; set; }
    }
}
