//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Web.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAIEMENT
    {
        public PAIEMENT()
        {
            this.T_E_PARTICIPATION_PAR1 = new HashSet<PARTICIPATION>();
        }
    
        public int PAI_ID { get; set; }
        public int PAR_ID { get; set; }
        public Nullable<int> CLU_ID { get; set; }
        public int COR_ID { get; set; }
        public int PAS_ID { get; set; }
        public Nullable<int> COU_ID { get; set; }
        public int PAI_MONTANT { get; set; }
        public string PAI_MOYENPAIEMENT { get; set; }
        public System.DateTime PAI_DATEPAIEMENT { get; set; }
    
        public virtual PARTICIPATION T_E_PARTICIPATION_PAR { get; set; }
        public virtual ICollection<PARTICIPATION> T_E_PARTICIPATION_PAR1 { get; set; }
    }
}
