//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Web.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPATION
    {
        public int PAR_ID { get; set; }
        public int COU_ID { get; set; }
        public int COR_ID { get; set; }
        public int PAI_ID { get; set; }
        public Nullable<bool> PAR_PASTAPARTY { get; set; }
        public Nullable<int> PAR_TEMPSESTIME { get; set; }
        public Nullable<int> PAR_NOMBREPASTAPARTY { get; set; }
        public int PAR_DOSSARD { get; set; }
    
        public virtual COUREUR T_E_COUREUR_COU { get; set; }
        public virtual PAIEMENT T_E_PAIEMENT_PAI { get; set; }
        public virtual COURSE T_R_COURSE_COR { get; set; }
    }
}
