//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Web.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPATIONENGROUPE
    {
        public int PEG_ID { get; set; }
        public int COU_ID { get; set; }
        public int CLU_ID { get; set; }
        public int PAI_ID { get; set; }
        public Nullable<int> PEG_NOMBREPARTICIPANT { get; set; }
        public Nullable<int> PEG_NOMBREPASTAPARTY { get; set; }
    
        public virtual PAIEMENT T_E_PAIEMENT_PAI { get; set; }
        public virtual CLUB T_R_CLUB_CLU { get; set; }
        public virtual COURSE T_R_COURSE_COR { get; set; }
    }
}
