//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Web.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_INSCRIT_INS
    {
        public int INS_ID { get; set; }
        public string INS_LOGIN { get; set; }
        public string INS_MDP { get; set; }
        public int INS_NIVEAUATHENTIFICATION { get; set; }
    }
}
