//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWebTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarathonEntititesTest : DbContext
    {
        public MarathonEntititesTest()
            : base("name=MarathonEntititesTest")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_E_COUREUR_COU> T_E_COUREUR_COU { get; set; }
        public virtual DbSet<T_E_INFORMATIONPUBLIQUE_INF> T_E_INFORMATIONPUBLIQUE_INF { get; set; }
        public virtual DbSet<T_E_INSCRIT_INS> T_E_INSCRIT_INS { get; set; }
        public virtual DbSet<T_E_PAIEMENT_PAI> T_E_PAIEMENT_PAI { get; set; }
        public virtual DbSet<T_E_PARTICIPATION_PAR> T_E_PARTICIPATION_PAR { get; set; }
        public virtual DbSet<T_E_PASTAPARTY_PAS> T_E_PASTAPARTY_PAS { get; set; }
        public virtual DbSet<T_J_CLASSEMENT_CLA> T_J_CLASSEMENT_CLA { get; set; }
        public virtual DbSet<T_J_TEMPSCOUBORNE_TCB> T_J_TEMPSCOUBORNE_TCB { get; set; }
        public virtual DbSet<T_R_BORNE_BOR> T_R_BORNE_BOR { get; set; }
        public virtual DbSet<T_R_CATEGORIE_CAT> T_R_CATEGORIE_CAT { get; set; }
        public virtual DbSet<T_R_CLUB_CLU> T_R_CLUB_CLU { get; set; }
        public virtual DbSet<T_R_COURSE_COR> T_R_COURSE_COR { get; set; }
        public virtual DbSet<T_R_DEFI_DEF> T_R_DEFI_DEF { get; set; }
        public virtual DbSet<T_R_FEDERATION_FED> T_R_FEDERATION_FED { get; set; }
        public virtual DbSet<T_R_LOT_LOT> T_R_LOT_LOT { get; set; }
    }
}
