//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWebTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_PAIEMENT_PAI
    {
        public T_E_PAIEMENT_PAI()
        {
            this.T_E_PARTICIPATION_PAR1 = new HashSet<T_E_PARTICIPATION_PAR>();
        }
    
        public int PAI_ID { get; set; }
        public int PAR_ID { get; set; }
        public int PAI_MONTANT { get; set; }
        public string PAI_MOYENPAIEMENT { get; set; }
        public System.DateTime PAI_DATEPAIEMENT { get; set; }
    
        public virtual T_E_PARTICIPATION_PAR T_E_PARTICIPATION_PAR { get; set; }
        public virtual ICollection<T_E_PARTICIPATION_PAR> T_E_PARTICIPATION_PAR1 { get; set; }
    }
}
