//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWebTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_PASTAPARTY_PAS
    {
        public T_E_PASTAPARTY_PAS()
        {
            this.T_E_PARTICIPATION_PAR = new HashSet<T_E_PARTICIPATION_PAR>();
        }
    
        public int PAS_ID { get; set; }
        public Nullable<int> PAS_NBMAXPARTICIPANT { get; set; }
    
        public virtual ICollection<T_E_PARTICIPATION_PAR> T_E_PARTICIPATION_PAR { get; set; }
    }
}
