//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWebTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_COUREUR_COU
    {
        public T_E_COUREUR_COU()
        {
            this.T_E_PARTICIPATION_PAR = new HashSet<T_E_PARTICIPATION_PAR>();
            this.T_J_CLASSEMENT_CLA = new HashSet<T_J_CLASSEMENT_CLA>();
            this.T_J_TEMPSCOUBORNE_TCB = new HashSet<T_J_TEMPSCOUBORNE_TCB>();
            this.T_R_LOT_LOT = new HashSet<T_R_LOT_LOT>();
            this.T_R_DEFI_DEF = new HashSet<T_R_DEFI_DEF>();
        }
    
        public int COU_ID { get; set; }
        public int INS_ID { get; set; }
        public Nullable<int> FED_ID { get; set; }
        public Nullable<int> CLU_ID { get; set; }
        public int CAT_ID { get; set; }
        public string COU_NOM { get; set; }
        public string COU_PRENOM { get; set; }
        public System.DateTime COU_DATENAISSANCE { get; set; }
        public string COU_SEXE { get; set; }
        public string COU_NUMEROLICENCE { get; set; }
        public string COU_EMAIL { get; set; }
        public string COU_ADRESSE { get; set; }
        public string COU_CODEPOSTAL { get; set; }
        public string COU_VILLE { get; set; }
        public string COU_PAYS { get; set; }
        public string COU_TELEPHONE { get; set; }
        public string COU_FAX { get; set; }
        public string COU_ENTREPRISEGROUPEASSOCIATION { get; set; }
        public string COU_CERTIFICATMEDICAL { get; set; }
        public string COU_FEDERATION { get; set; }
    
        public virtual T_R_FEDERATION_FED T_R_FEDERATION_FED { get; set; }
        public virtual T_R_CLUB_CLU T_R_CLUB_CLU { get; set; }
        public virtual T_R_CATEGORIE_CAT T_R_CATEGORIE_CAT { get; set; }
        public virtual T_E_INSCRIT_INS T_E_INSCRIT_INS { get; set; }
        public virtual ICollection<T_E_PARTICIPATION_PAR> T_E_PARTICIPATION_PAR { get; set; }
        public virtual ICollection<T_J_CLASSEMENT_CLA> T_J_CLASSEMENT_CLA { get; set; }
        public virtual ICollection<T_J_TEMPSCOUBORNE_TCB> T_J_TEMPSCOUBORNE_TCB { get; set; }
        public virtual ICollection<T_R_LOT_LOT> T_R_LOT_LOT { get; set; }
        public virtual ICollection<T_R_DEFI_DEF> T_R_DEFI_DEF { get; set; }
    }
}
