//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWebTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_INFORMATIONPUBLIQUE_INF
    {
        public int INF_ID { get; set; }
        public string INF_NOM { get; set; }
        public string INF_PRENOM { get; set; }
        public string INF_EMAIL { get; set; }
        public string INF_CONTENUE { get; set; }
        public string INF_TITRE { get; set; }
    }
}
