//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWebTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_PARTICIPATION_PAR
    {
        public T_E_PARTICIPATION_PAR()
        {
            this.T_E_PAIEMENT_PAI = new HashSet<T_E_PAIEMENT_PAI>();
        }
    
        public int PAR_ID { get; set; }
        public int CLU_ID { get; set; }
        public int COR_ID { get; set; }
        public int PAS_ID { get; set; }
        public int COU_ID { get; set; }
        public Nullable<int> PAI_ID { get; set; }
        public int PAR_DOSSARD { get; set; }
        public Nullable<int> PAR_TEMPS_ESTIME { get; set; }
        public int PAR_NBPARTICIPANTCOURSE { get; set; }
        public bool PAR_PARTICIPEPASTAPARTY { get; set; }
        public int PAR_NBPARTICIPANTPASTAPARTY { get; set; }
    
        public virtual T_E_COUREUR_COU T_E_COUREUR_COU { get; set; }
        public virtual ICollection<T_E_PAIEMENT_PAI> T_E_PAIEMENT_PAI { get; set; }
        public virtual T_E_PAIEMENT_PAI T_E_PAIEMENT_PAI1 { get; set; }
        public virtual T_R_COURSE_COR T_R_COURSE_COR { get; set; }
        public virtual T_E_PASTAPARTY_PAS T_E_PASTAPARTY_PAS { get; set; }
        public virtual T_R_CLUB_CLU T_R_CLUB_CLU { get; set; }
    }
}
