//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWebTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_R_CATEGORIE_CAT
    {
        public T_R_CATEGORIE_CAT()
        {
            this.T_E_COUREUR_COU = new HashSet<T_E_COUREUR_COU>();
        }
    
        public int CAT_ID { get; set; }
        public string CAT_LIBELLE { get; set; }
        public string CAT_CODE { get; set; }
    
        public virtual ICollection<T_E_COUREUR_COU> T_E_COUREUR_COU { get; set; }
    }
}
