//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWebTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_R_BORNE_BOR
    {
        public T_R_BORNE_BOR()
        {
            this.T_J_TEMPSCOUBORNE_TCB = new HashSet<T_J_TEMPSCOUBORNE_TCB>();
        }
    
        public int BOR_ID { get; set; }
        public int COR_ID { get; set; }
        public int BOR_EMPLACEMENT { get; set; }
    
        public virtual ICollection<T_J_TEMPSCOUBORNE_TCB> T_J_TEMPSCOUBORNE_TCB { get; set; }
        public virtual T_R_COURSE_COR T_R_COURSE_COR { get; set; }
    }
}
