//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWebTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_R_CLUB_CLU
    {
        public T_R_CLUB_CLU()
        {
            this.T_E_COUREUR_COU = new HashSet<T_E_COUREUR_COU>();
            this.T_E_PARTICIPATION_PAR = new HashSet<T_E_PARTICIPATION_PAR>();
        }
    
        public int CLU_ID { get; set; }
        public Nullable<int> FED_ID { get; set; }
        public int INS_ID { get; set; }
        public string CLU_NOM { get; set; }
        public string CLU_LICENCE { get; set; }
        public string CLU_EMAIL { get; set; }
        public string CLU_ADRESSE { get; set; }
        public string CLU_CODEPOSTAL { get; set; }
        public string CLU_VILLE { get; set; }
        public string CLU_PAYS { get; set; }
        public string CLU_TELEPHONE { get; set; }
        public string CLU_FAX { get; set; }
        public string CLU_NUMERO { get; set; }
    
        public virtual ICollection<T_E_COUREUR_COU> T_E_COUREUR_COU { get; set; }
        public virtual T_E_INSCRIT_INS T_E_INSCRIT_INS { get; set; }
        public virtual ICollection<T_E_PARTICIPATION_PAR> T_E_PARTICIPATION_PAR { get; set; }
        public virtual T_R_FEDERATION_FED T_R_FEDERATION_FED { get; set; }
    }
}
