//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWebTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_R_DEFI_DEF
    {
        public T_R_DEFI_DEF()
        {
            this.T_R_COURSE_COR = new HashSet<T_R_COURSE_COR>();
            this.T_E_COUREUR_COU = new HashSet<T_E_COUREUR_COU>();
        }
    
        public int DEF_ID { get; set; }
        public string DEF_NOM { get; set; }
        public int DEF_NOMBREMAXPARTICIPANT { get; set; }
        public string DEF_EXPLICATION { get; set; }
    
        public virtual ICollection<T_R_COURSE_COR> T_R_COURSE_COR { get; set; }
        public virtual ICollection<T_E_COUREUR_COU> T_E_COUREUR_COU { get; set; }
    }
}
