//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWebTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_R_FEDERATION_FED
    {
        public T_R_FEDERATION_FED()
        {
            this.T_E_COUREUR_COU = new HashSet<T_E_COUREUR_COU>();
            this.T_R_CLUB_CLU = new HashSet<T_R_CLUB_CLU>();
        }
    
        public int FED_ID { get; set; }
        public string FED_NOM { get; set; }
    
        public virtual ICollection<T_E_COUREUR_COU> T_E_COUREUR_COU { get; set; }
        public virtual ICollection<T_R_CLUB_CLU> T_R_CLUB_CLU { get; set; }
    }
}
