//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWebTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_R_COURSE_COR
    {
        public T_R_COURSE_COR()
        {
            this.T_E_PARTICIPATION_PAR = new HashSet<T_E_PARTICIPATION_PAR>();
            this.T_J_CLASSEMENT_CLA = new HashSet<T_J_CLASSEMENT_CLA>();
            this.T_R_BORNE_BOR = new HashSet<T_R_BORNE_BOR>();
            this.T_R_DEFI_DEF = new HashSet<T_R_DEFI_DEF>();
        }
    
        public int COR_ID { get; set; }
        public string COR_NOM { get; set; }
        public int COR_DISTANCE { get; set; }
        public Nullable<System.DateTime> COR_DATE { get; set; }
        public Nullable<int> COR_NOMBREMAXPARTICIPANT { get; set; }
        public Nullable<decimal> COR_PRIX { get; set; }
    
        public virtual ICollection<T_E_PARTICIPATION_PAR> T_E_PARTICIPATION_PAR { get; set; }
        public virtual ICollection<T_J_CLASSEMENT_CLA> T_J_CLASSEMENT_CLA { get; set; }
        public virtual ICollection<T_R_BORNE_BOR> T_R_BORNE_BOR { get; set; }
        public virtual ICollection<T_R_DEFI_DEF> T_R_DEFI_DEF { get; set; }
    }
}
